export default {
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  GET_INPUT: 'GET_INPUT',
  TOGGLE_SEARCH_RESULT: 'TOGGLE_SEARCH_RESULT',
  ADD_INTERMEDIATE_POINT: 'ADD_INTERMEDIATE_POINT',
  REMOVE_INTERMEDIATE_POINT: 'REMOVE_INTERMEDIATE_POINT',
  GET_ADDRESS_PREDICTIONS: 'GET_ADDRESS_PREDICTIONS',
  GET_SELECTED_ADDRESS: 'GET_SELECTED_ADDRESS',
  BUILD_ROUTE: 'BUILD_ROUTE',
  GET_DISTANCE_MATRIX: 'GET_DISTANCE_MATRIX',
};
