const IMAGE = {
  ICON_HOME: require('../../images/home.png'),
  ICON_HOME_BLACK: require('../../images/home-black.png'),
  ICON_PROFILE: require('../../images/profile.png'),
  ICON_PROFILE_BLACK: require('../../images/profile-black.png'),
  ICON_SETTINGS: require('../../images/settings.png'),
  ICON_CATALOG: require('../../images/catalog.png'),
  ICON_REGISTER: require('../../images/register.png'),
  ICON_LOGIN: require('../../images/login.png'),
  ICON_LOGOUT: require('../../images/logout.png'),
  ICON_EYE: require('../../images/eye.png'),
  ICON_EYEHIDE: require('../../images/eyehide.png'),
  ICON_HELP: require('../../images/help.png'),
  ICON_LANGUAGE: require('../../images/language.png'),
  ICON_PROFILE_MAIN: require('../../images/profile-main.png'),
  ICON_BACK: require('../../images/back.png'),
  ICON_OPEN_MENU: require('../../images/open-menu.png'),
  ICON_RADIO_CHECKED: require('../../images/radio-checked.png'),
  ICON_RADIO_UNCHECKED: require('../../images/radio-unchecked.png'),
  ICON_WORLD: require('../../images/worldwide.png'),
  ICON_WORLD_BLACK: require('../../images/worldwide-black.png'),
  ICON_MARKER: require('../../images/marker.png'),
  ICON_GEOLOCATION: require('../../images/geolocation.png'),
  ICON_PLUS: require('../../images/plus.png'),
  ICON_CROSS: require('../../images/cross.png'),
  ICON_TIME: require('../../images/time.png'),
  ICON_DISTANCE: require('../../images/distance.png'),
  ICON_GENERAL_ROAD_CONDITION: require('../../images/general-road-condition.png'),
  ICON_SEND_COMMENT: require('../../images/send-comment.png'),
  ICON_STAR: require('../../images/star.png'),
  ICON_CLOSE: require('../../images/close.png'),
  ICON_CHECK: require('../../images/check.png'),
};

export {IMAGE};
